### ISSUE TITLE
Getting warning from plugin

### ISSUE THREAD

**Issue by toxicclowd** [artpi/wp-dao#5]
getting the following warning after installing the plugin, tried to fix it but i'm only a novice programmer and not too familiar with PHP or wordpress development.

Warning
: call_user_func_array() expects parameter 1 to be a valid callback, function 'Artpi\WPDAOmembers_only_caps' not found or invalid function name in
/home/pixonix/thegameblast.com/wp-includes/class-wp-hook.php
on line
303

Tried to silence the warning in WP_CONFIG but still pops up in backend and on login page.

**Comment by artpi** [comment]
Hey @toxicclowd ! You are right, there was a rebase issue. I just pushed a fix and will do a new release soon
